baseURL = 'https://kasterling.github.io/kona-blog/'
languageCode = 'en-us'
title = 'ğŸï¸ Kona Adventures'
theme = 'hugo-theme-walden'
publishDir = 'public'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[pagination]
  disableAliases = false
  pagerSize = 12
  path = 'page'

[params]
  author = "Keith Sterling"
  description = "Adventures and memories from my trip to Kona, Hawaii ğŸŒº"
  multiLingual = false
    
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.129.0"